apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: previews
spec:
  ingressClassName: contour
  # tls:
  #   - hosts:
  #       - *.previews.bene.dev
  #     secretName: hello-kubernetes-tls
  rules:
    - host: project1.previews.solidlabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project1
                port:
                  number: 80
