name: Sync sections with CMS
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bunx inhalt-sync
        env:
          INHALT_URL: "https://cms.bene.dev"
